import AdminTopBar from "@/components/admin-topbar";
import SideNavbar from "@/components/side-nav";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <AdminTopBar />
      <div className="flex grow  h-full w-full absolute top-20">
        <SideNavbar />
        <div className="w-5/6">{children}</div>
      </div>
    </>
  );
};

export default layout;
