import AdminTopBar from "@/components/admin-topbar";
import TopBar from "@/components/topbar";
import AuthSessionProvider from "@/providers/session-provider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { authOptions } from "./api/auth/[...nextauth]/options";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        {session?.user.role === "ADMIN" ? <AdminTopBar /> : <TopBar />}

        <AuthSessionProvider>{children}</AuthSessionProvider>
      </body>
    </html>
  );
}
